---
- name: Install AWS CLI on remote instance
  hosts: all
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name: [unzip, curl]
        state: present
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      yum:
        name: [unzip, curl]
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: ./aws/install
      args:
        chdir: /tmp

    - name: Check AWS CLI version
      command: aws --version
      register: aws_cli_version

    - name: Show installed AWS CLI version
      debug:
        msg: "{{ aws_cli_version.stdout }}"
